server:
  port: 3344                  #端口号


spring:
  application:
    name: config-server      #服务名称
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Json-spec/springcloud-config.git          #分布式配置中心配置文件的远程仓库的地址
          #username: 1654624759@qq.com                                      #github账号
          #password: 52013145257LSs                                         #github密码     注如果git仓库是私有的需要配置用户名密码公开的不需要配置
          search-paths: springcloud-config                                 #配置远程仓库读取路径
      label: master                                                        #配置仓库的分支
  #解决从git上获取信息中文乱码问题配置
  http:                                                                    #解决分布式配置中心读取远程配置出现中文乱码的情况
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  #rabbitmq中15672是web网页访问的端口，5672是mq访问的端口
  rabbitmq:                                      #消息队列的配置
    username: guest
    password: guest
    host: localhost
    port: 5672

#使用消息队列需要对端口暴露
management:
  endpoints:
    web:
      exposure:
        include: "*"

#注册中心配置
eureka:
  instance:
    hostname: localhost                                                                               #主机名称可以是ip
  client:
    fetch-registry: true                                                                              # 是否拉取其它服务的信息，默认是true
    register-with-eureka: true                                                                        # 是否注册自己的信息到EurekaServer，默认是true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:7001/eureka/                                    #指定服务客户端要注册到那个注册中的具体地址


#访问地址例如； http://localhost:3344/config-dev.yml    ,    http://localhost:3344/config-test.yml   可在浏览器中看见git仓库配置的具体配置信息(springcloud-config服务端访问)
#启动分布式注册中心服务可通过一下方式进行访问远程配置
 # /{application}/{profile}[/{label}]
 # /{application}-{profile}.yml
 # /{label}/{application}-{profile}.yml
 # /{application}-{profile}.properties
 # /{label}/{application}-{profile}.properties
#label : git仓库的分支
#application ：配置文件的文件名，如我的残酷里的clientOne.yml 中的“clientOne”，对应服务的应用名，这个后面再说
#profile：这个很熟悉，配置文件的后缀，可以对应服务启用的环境
#访问配置文件
#默认访问
#默认访问的是master分支



#自动刷新配置
#通常使用rabbitmq/kafka等消息队列配合config分布式配置中心一起使用
#1> 通常有两种方式一种是使用刷新客户端然后遍布到所有的客户端实现刷新 ，另一种方式是刷新springcloudconfig的服务端的形式然后发送一个post请求 curl -X POST "http://localhost:3344/actuator/bus-refresh"刷新服务端然后所有的客户端从而刷新 通常采用第二种方式
#2> springcloudConfig通常了SpringcloudBus一起使用用过消息队列的形式进行配置的自动刷新
