server:
  port: 8004

spring:
  application:
    name: zookeeper-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource                                                      #当前数据库操作类型
    driver-class-name: com.mysql.jdbc.Driver                                                          #mysql驱动包
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&usrSSL=false        #mysql的url


  cloud:
    zookeeper:
      connect-string:  127.0.0.1:2181




mybatis:
  mapper-locations: classpath:mapper/*.Mapper.xml
