#------------------------------基础配置----------------------------------------------------------------------------------
server:
  port: 8006                                                                                #端口号

spring:
  application:
    name: cloud-providerForConsul-paymentServer8006                                          #此服务名称(必须要配置)

#-------------------------------Consul服务注册中心相关配置---------------------------------------------------------------------

    #logging:
    #config: classpath:log4j2-test.xml                                                            #指定日志文件的位置
    #level:
    #com.atguigu.springcloud: debug
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
