server:
  port: 90

spring:
  application:
    name: consumer-server90

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  #配置Nacos地址服务像这个地址注册     nacos图形化界面:http://127.0.0.1:8848/nacos/index.html


server-url:
  nacos-user-server: http://alibaba-server                #次服务使用restTemplate调用的服务提供者的服务名称通过配置文件配置取 之前是在代码中定义常量写死的此种方法更加优雅
