#---------------------------基础配置必须要陪-----------------------------------------------------------------------------
server:
  port: 8002                                                                                          #端口号

spring:
  application:
    name: cloud-payment-service                                                                       #服务名称（必须要配置）
  #----------------------------数据源相关配置------------------------------------------------------------------------------
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource                                                      #当前数据库操作类型
    driver-class-name: com.mysql.jdbc.Driver                                                          #mysql驱动包
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&usrSSL=false        #mysql的url
#------------------------------注册中心相关配置--------------------------------------------------------------------------
eureka:
  instance:
    hostname: localhost                                                                               #主机名称可以是ip
  client:
    fetch-registry: true                                                                              # 是否拉取其它服务的信息，默认是true
    register-with-eureka: true                                                                        # 是否注册自己的信息到EurekaServer，默认是true
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka                #指定服务客户端要注册到那个注册中的具体地址(集群版需要在defaultZone后面列出所有注册中心服务端地址服务分别注册到每一个注册中心，注册中心地址以逗号分隔）



#------------------------------mybatis相关配置--------------------------------------------------------------------------
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml                                                      #mapper配置文件位置
  type-aliases-package: com.atguigu.springcloud.entityes                                              #指定实体类别名所在的包路径

ribbon:               #openFegin默认等待一秒钟超时因此需要设置openFegin的超时时间（openFegin整合了ribbon因此超时间时间由ribbon控制）
  ReadTimeout: 6000   #设置openFegin读取时间(建立连接所用时间)适用于网络正常的情况下，两端所用的时间
  ConnectTimeout: 6000   #建立后从服务器读取到可用资源所用的时间

logging:
  #config: classpath:log4j2-test.xml                                                                  #指定日志文件的位置
  level:
    com.atguigu.springcloud.mapper: debug                                                             #指定日志级别为debug(level的下一层级代表的是包的路径最好配置为服务的父路径这样可以扫描所有文件)

